# Generated by Django 4.1.7 on 2023-03-02 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(help_text='Unique id for clients', primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('code', models.CharField(default='0000', max_length=4, unique=True)),
                ('is_used', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date client joined')),
                ('code_date_send', models.DateTimeField(auto_now_add=True, help_text='Date code send to client')),
            ],
        ),
        migrations.CreateModel(
            name='LegalUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('organization_type', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_address', models.CharField(max_length=200)),
                ('INN', models.CharField(max_length=12)),
                ('KPP', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User provided name for plugin', max_length=200)),
                ('document_count', models.IntegerField(default=0, help_text='Number of documents filled with plugin')),
                ('unique_users_attracted', models.IntegerField(default=0, help_text='Number of attracted unique users')),
                ('plugin_id', models.UUIDField(help_text='Unique id for plugin', unique=True)),
                ('plugin_secret', models.UUIDField(help_text='Secret used verify plugin')),
                ('valid_until_date', models.DateField(help_text='Plugin valid until this date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
